stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - Iris.data

  process_data:
    cmd: python process_data.py
    deps:
    - process_data.py
    - Iris.data
    outs:
    - data_processed.csv

  train:
    cmd: python train.py
    deps:
    - train.py
    - data_processed.csv
    - labels.csv
    metrics:
    - metrics.json:
        cache: false
